language: go

os:
  - linux
  - osx

sudo: required

go:
  - 1.7
  - 1.8
  - tip

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -q libpcap-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libpcap ; fi

install: make install_ci

script: make test

cache:
  directories:
    - vendor
