language: go
sudo: required
go:
  - 1.6
  - 1.7
  - tip
env:
  global:
    - UBER_ENVIRONMENT=production
    - UBER_CONFIG_DIR=./daemon/config
install: make install_ci
script: make test
cache:
  directories:
    - vendor

