language: go
sudo: required
go:
  - 1.7
  - tip
env:
  global:
    - ENVIRONMENT=production
    - CONFIG_DIR=./daemon/config
install: make install_ci
script: make test
cache:
  directories:
    - vendor
