language: go

os:
  - linux
  - osx

sudo: required

go:
  - 1.7
  - 1.8
  - tip

before_install:
  - sudo apt-get install -q libpcap-dev

install: make install_ci

script: make test

cache:
  directories:
    - vendor
